config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "flats#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, :img, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :img)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <%= render '/shared/form', flat: @flat %>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
        <p>All <%= @flats.all.size %> flats.</p>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
        <div class="col-4">
          <div class="flat-card">
            <div class="flat-card-image" style="background-image: url(<%= flat.img %>)"></div>
            <div class="flat-card-content">
              <div class="flat-card-title">
                <h4><%= flat.name %></h4>
              </div>
              <p><%= flat.address %></p>
              <div class="d-flex">
                <div class="d-flex">
                  <i class="icon-group mr-2"></i><span><%= flat.number_of_guests %></span>
                </div>
                <div class="d-flex ml-3">
                  <i class="icon-eur mr-2"></i> <%= flat.price_per_night %>
                </div>
              </div>
            </div>
            <div class="flat-card-actions">
              <%= link_to  "More info", flat_path(flat) %>
              <%= link_to "Edit", edit_flat_path(flat), class: "ml-3 text-warning" %>
              <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" }, class: "ml-3 text-danger" %>
            </div>
          </div>
        </div>
    <% end %>
  </div>

</div>

app/views/flats/new.html.erb
<div class="container">
  <%= render '/shared/form', flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url(<%= @flat.img %>)"></div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
        <div class="map"></div>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="d-flex">
          <div class="d-flex">
            <i class="icon-group mr-2"></i><span><%= @flat.number_of_guests %></span>
          </div>
          <div class="d-flex ml-3">
            <i class="icon-eur mr-2"></i> <%= @flat.price_per_night %>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="d-flex align-items-center justify-content-between">
          <h6 class="mb-0">Share</h6>

          <div class="d-flex">
            <i class="icon-facebook-sign mr-2"></i>
            <i class="icon-twitter-sign mr-2"></i>
            <i class="icon-pinterest-sign mr-2"></i>
            <i class="icon-envelope"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Simple Airbnb</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto d-flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
        </div>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/shared/_form.html.erb
<%= simple_form_for flat do |f| %>
  <div class="form-group">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description, as: :text %>
    <%= f.input :price_per_night, as: :integer %>
    <%= f.input :number_of_guests, as: :integer %>
    <%= f.input :img %>
  </div>
  <%= f.submit "Submit flat", class: "btn btn-primary" %>
<% end %>